
export const LIST_PRODUCT = 'LIST_PRODUCT';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const GET_PRODUCT = 'GET_PRODUCT';
export const GET_CART = 'GET_CART';
export const DELETE_ITEM_IN_CART = 'DELETE_ITEM_IN_CART';
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const UPDATE_QUANTITY_ITEM = 'UPDATE_QUANTITY_ITEM';
export const LOGIN = 'LOGIN';
export const ADD_PRODUCT_TO_WISHLIST = 'ADD_PRODUCT_TO_WISHLIST';
export const DELETE_ITEM_IN_WISHLIST = 'DELETE_ITEM_IN_WISHLIST';
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS';
export const GET_LIST_CATEGORY = 'GET_LIST_CATEGORY';
export const GET_PRODUCTS_WITH_CATEGORY = 'GET_PRODUCTS_WITH_CATEGORY';
export const GET_DIFFER_PRODUCTS_WITH_CATEGORY = 'GET_DIFFER_PRODUCTS_WITH_CATEGORY';